/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YogaRouteImport } from './routes/yoga'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AstrologiaRouteImport } from './routes/astrologia'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YogaSlugRouteImport } from './routes/yoga.$slug'
import { Route as DiarioSlugRouteImport } from './routes/diario.$slug'
import { Route as AstrologiaSlugRouteImport } from './routes/astrologia.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const YogaRoute = YogaRouteImport.update({
  id: '/yoga',
  path: '/yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologiaRoute = AstrologiaRouteImport.update({
  id: '/astrologia',
  path: '/astrologia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaSlugRoute = YogaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => YogaRoute,
} as any)
const DiarioSlugRoute = DiarioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DiarioRoute,
} as any)
const AstrologiaSlugRoute = AstrologiaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AstrologiaRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/astrologia': typeof AstrologiaRouteWithChildren
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/diario': typeof DiarioRouteWithChildren
  '/eventos': typeof EventosRoute
  '/recursos': typeof RecursosRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-mi': typeof SobreMiRoute
  '/yoga': typeof YogaRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/astrologia/$slug': typeof AstrologiaSlugRoute
  '/diario/$slug': typeof DiarioSlugRoute
  '/yoga/$slug': typeof YogaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/astrologia': typeof AstrologiaRouteWithChildren
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/diario': typeof DiarioRouteWithChildren
  '/eventos': typeof EventosRoute
  '/recursos': typeof RecursosRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-mi': typeof SobreMiRoute
  '/yoga': typeof YogaRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/astrologia/$slug': typeof AstrologiaSlugRoute
  '/diario/$slug': typeof DiarioSlugRoute
  '/yoga/$slug': typeof YogaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/astrologia': typeof AstrologiaRouteWithChildren
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/diario': typeof DiarioRouteWithChildren
  '/eventos': typeof EventosRoute
  '/recursos': typeof RecursosRoute
  '/servicios': typeof ServiciosRoute
  '/sobre-mi': typeof SobreMiRoute
  '/yoga': typeof YogaRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/astrologia/$slug': typeof AstrologiaSlugRoute
  '/diario/$slug': typeof DiarioSlugRoute
  '/yoga/$slug': typeof YogaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/astrologia'
    | '/auth'
    | '/contacto'
    | '/diario'
    | '/eventos'
    | '/recursos'
    | '/servicios'
    | '/sobre-mi'
    | '/yoga'
    | '/admin'
    | '/astrologia/$slug'
    | '/diario/$slug'
    | '/yoga/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/astrologia'
    | '/auth'
    | '/contacto'
    | '/diario'
    | '/eventos'
    | '/recursos'
    | '/servicios'
    | '/sobre-mi'
    | '/yoga'
    | '/admin'
    | '/astrologia/$slug'
    | '/diario/$slug'
    | '/yoga/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/astrologia'
    | '/auth'
    | '/contacto'
    | '/diario'
    | '/eventos'
    | '/recursos'
    | '/servicios'
    | '/sobre-mi'
    | '/yoga'
    | '/_authenticated/admin'
    | '/astrologia/$slug'
    | '/diario/$slug'
    | '/yoga/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AstrologiaRoute: typeof AstrologiaRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactoRoute: typeof ContactoRoute
  DiarioRoute: typeof DiarioRouteWithChildren
  EventosRoute: typeof EventosRoute
  RecursosRoute: typeof RecursosRoute
  ServiciosRoute: typeof ServiciosRoute
  SobreMiRoute: typeof SobreMiRoute
  YogaRoute: typeof YogaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yoga': {
      id: '/yoga'
      path: '/yoga'
      fullPath: '/yoga'
      preLoaderRoute: typeof YogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrologia': {
      id: '/astrologia'
      path: '/astrologia'
      fullPath: '/astrologia'
      preLoaderRoute: typeof AstrologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga/$slug': {
      id: '/yoga/$slug'
      path: '/$slug'
      fullPath: '/yoga/$slug'
      preLoaderRoute: typeof YogaSlugRouteImport
      parentRoute: typeof YogaRoute
    }
    '/diario/$slug': {
      id: '/diario/$slug'
      path: '/$slug'
      fullPath: '/diario/$slug'
      preLoaderRoute: typeof DiarioSlugRouteImport
      parentRoute: typeof DiarioRoute
    }
    '/astrologia/$slug': {
      id: '/astrologia/$slug'
      path: '/$slug'
      fullPath: '/astrologia/$slug'
      preLoaderRoute: typeof AstrologiaSlugRouteImport
      parentRoute: typeof AstrologiaRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AstrologiaRouteChildren {
  AstrologiaSlugRoute: typeof AstrologiaSlugRoute
}

const AstrologiaRouteChildren: AstrologiaRouteChildren = {
  AstrologiaSlugRoute: AstrologiaSlugRoute,
}

const AstrologiaRouteWithChildren = AstrologiaRoute._addFileChildren(
  AstrologiaRouteChildren,
)

interface DiarioRouteChildren {
  DiarioSlugRoute: typeof DiarioSlugRoute
}

const DiarioRouteChildren: DiarioRouteChildren = {
  DiarioSlugRoute: DiarioSlugRoute,
}

const DiarioRouteWithChildren =
  DiarioRoute._addFileChildren(DiarioRouteChildren)

interface YogaRouteChildren {
  YogaSlugRoute: typeof YogaSlugRoute
}

const YogaRouteChildren: YogaRouteChildren = {
  YogaSlugRoute: YogaSlugRoute,
}

const YogaRouteWithChildren = YogaRoute._addFileChildren(YogaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AstrologiaRoute: AstrologiaRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactoRoute: ContactoRoute,
  DiarioRoute: DiarioRouteWithChildren,
  EventosRoute: EventosRoute,
  RecursosRoute: RecursosRoute,
  ServiciosRoute: ServiciosRoute,
  SobreMiRoute: SobreMiRoute,
  YogaRoute: YogaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
